import fs from "node:fs/promises";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const root = process.cwd();
const args = process.argv.slice(2);
const yes = args.includes("--yes") || args.includes("-y");
const positional = args.find((arg) => !arg.startsWith("-"));
if (args.includes("--help") || args.includes("-h")) {
  console.log("Usage: create-my-pwa <project-name> [--yes]");
  console.log(
    "Generate a React + TypeScript + Vite PWA with optional Firebase and Android TWA setup.",
  );
  process.exit(0);
}
if (args.includes("--version") || args.includes("-v")) {
  console.log("create-my-pwa 0.1.0");
  process.exit(0);
}

const ask = async (rl, question, fallback) => {
  if (yes) return fallback;
  const answer = await rl.question(
    `${question} ${fallback ? `[${fallback}] ` : ""}`,
  );
  return answer.trim() || fallback;
};
const confirm = async (rl, question, fallback = true) =>
  (await ask(rl, `${question} (y/n)`, fallback ? "y" : "n"))
    .toLowerCase()
    .startsWith("y");
const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-|-$/g, "") || "my-pwa";
const write = async (base, file, content) => {
  const target = path.join(base, file);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content);
};

const react = (name) =>
  `import { useState } from 'react';\nimport { Link } from 'react-router-dom';\nimport { useInstallPrompt } from './hooks/useInstallPrompt';\n\nexport default function App() {\n  const [count, setCount] = useState(0);\n  const { canInstall, install } = useInstallPrompt();\n  return <main className="shell"><p className="eyebrow">CREATE-MY-PWA</p><h1>{name}</h1><p>Your React + Firebase PWA is ready.</p><div className="actions"><button onClick={() => setCount(count + 1)}>Clicked {count} times</button><Link to="/login">Auth starter</Link>{canInstall && <button onClick={install}>Install app</button>}</div></main>;\n}`;
const generatedReadme = (name, pm) => `# ${name}

Generated by create-my-pwa.

## Start here

### Prerequisites

- Node.js 18 or newer
- ${pm}
- Firebase CLI if Firebase was selected

Install Firebase CLI and sign in:

\`\`\`bash
npm install -g firebase-tools
firebase login
\`\`\`

Install dependencies and create your environment file:

\`\`\`bash
${pm} install
${pm === "npm" ? "copy" : "cp"} .env.example .env
${pm === "npm" ? "npm run dev" : `${pm} dev`}
\`\`\`

## Firebase setup

1. Open the [Firebase Console](https://console.firebase.google.com/) and create a project.
2. Open **Project settings**.
3. Under **Your apps**, choose the Web icon (\`</>\`) and register this app.
4. Open **SDK setup and configuration** and copy the web configuration values.
5. Enable the Firebase products selected during generation: Authentication providers, Firestore Database, Storage, and Functions as needed.
6. Connect this directory to the project:

\`\`\`bash
firebase use --add
\`\`\`

Select the project and use the \`default\` alias. The generated \`.firebaserc\` contains a placeholder until you connect it.

## Environment configuration

Fill the root \`.env\` with the exact values from Firebase:

\`\`\`env
VITE_FIREBASE_API_KEY=your-api-key
VITE_FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=your-project-id
VITE_FIREBASE_STORAGE_BUCKET=your-project.firebasestorage.app
VITE_FIREBASE_MESSAGING_SENDER_ID=your-sender-id
VITE_FIREBASE_APP_ID=your-app-id
VITE_FIREBASE_VAPID_KEY=your-web-push-vapid-key
\`\`\`

The \`VITE_\` prefix is required by Vite. Never commit \`.env\`. Client Firebase configuration values are not passwords; protect data with Authentication, Firestore rules, Storage rules, and App Check.

## Development and validation

\`\`\`bash
${pm === "npm" ? "npm run dev" : `${pm} dev`}
${pm === "npm" ? "npm run build" : `${pm} run build`}
${pm === "npm" ? "npm run preview" : `${pm} run preview`}
\`\`\`

Review the generated Firestore and Storage rules before deployment. They are intentionally restrictive. Do not deploy public read/write rules.

## Firebase emulators

If Emulator Suite was selected:

\`\`\`bash
${pm === "npm" ? "npm run firebase:emulate" : `${pm} run firebase:emulate`}
\`\`\`

Configure the app to connect to the emulators during local development.

## Deployment

After selecting the correct Firebase project:

\`\`\`bash
${pm === "npm" ? "npm run deploy" : `${pm} run deploy`}
${pm === "npm" ? "npm run deploy:web" : `${pm} run deploy:web`}
${pm === "npm" ? "npm run deploy:functions" : `${pm} run deploy:functions`}
\`\`\`

Verify Hosting, Authentication, Firestore, Storage, and Functions in the Firebase Console after deployment.

## Android TWA (optional)

Install Bubblewrap after installing Java and Android Studio:

\`\`\`bash
npm install -g @bubblewrap/cli
\`\`\`

Deploy the PWA first, then set the deployed manifest URL:

Windows PowerShell:

\`\`\`powershell
$env:PWA_MANIFEST_URL = "https://your-project.web.app/manifest.webmanifest"
\`\`\`

macOS/Linux:

\`\`\`bash
export PWA_MANIFEST_URL=https://your-project.web.app/manifest.webmanifest
\`\`\`

Initialize and build:

\`\`\`bash
${pm === "npm" ? "npm run android:init" : `${pm} run android:init`}
${pm === "npm" ? "npm run android:build" : `${pm} run android:build`}
\`\`\`

Replace the placeholder SHA-256 fingerprint in \`public/.well-known/assetlinks.json\`, deploy it, and keep Android signing keys private.
`;

async function main() {
  const rl = readline.createInterface({ input, output });
  const requestedName =
    positional || (await ask(rl, "Project name?", "my-pwa"));
  const projectName = slug(requestedName);
  const packageManager = await ask(
    rl,
    "Package manager? (npm/pnpm/yarn)",
    "npm",
  );
  const pm = ["npm", "pnpm", "yarn"].includes(packageManager.toLowerCase())
    ? packageManager.toLowerCase()
    : "npm";
  const target = path.resolve(root, projectName);
  try {
    await fs.access(target);
    throw new Error(`Target already exists: ${target}`);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  const useFirebase = await confirm(rl, "Configure Firebase?", true);
  const firestore =
    useFirebase && (await confirm(rl, "Enable Firestore?", true));
  const storage = useFirebase && (await confirm(rl, "Enable Storage?", true));
  const functions =
    useFirebase && (await confirm(rl, "Enable Cloud Functions?", true));
  const hosting =
    useFirebase && (await confirm(rl, "Configure Hosting?", true));
  const emulator =
    useFirebase && (await confirm(rl, "Configure Emulator Suite?", true));
  const auth =
    useFirebase &&
    (await confirm(rl, "Generate Authentication helpers?", true));
  const android = await confirm(rl, "Create Android TWA configuration?", false);
  const packageName = android
    ? await ask(
        rl,
        "Android package name?",
        `com.example.${projectName.replaceAll("-", "")}`,
      )
    : "";
  rl.close();

  await write(
    target,
    "package.json",
    JSON.stringify(
      {
        name: projectName,
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: {
          dev: "vite",
          build: "tsc -b && vite build",
          preview: "vite preview",
          ...(emulator && { "firebase:emulate": "firebase emulators:start" }),
          ...(hosting && {
            deploy: "npm run build && firebase deploy",
            "deploy:web": "npm run build && firebase deploy --only hosting",
          }),
          ...(functions && {
            "deploy:functions": "firebase deploy --only functions",
          }),
          ...(android && {
            "android:init":
              "bubblewrap init --manifest=$PWA_MANIFEST_URL --directory=android",
            "android:build": "bubblewrap build --directory=android",
          }),
        },
        dependencies: {
          "@vitejs/plugin-react": "^4.3.1",
          firebase: "^11.0.0",
          react: "^18.3.1",
          "react-dom": "^18.3.1",
          "react-router-dom": "^6.28.0",
        },
        devDependencies: {
          typescript: "^5.6.3",
          vite: "^5.4.10",
          "vite-plugin-pwa": "^0.20.5",
        },
      },
      null,
      2,
    ) + "\n",
  );
  await write(
    target,
    "index.html",
    `<!doctype html><html><head><meta name="theme-color" content="#0f172a"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${projectName}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>`,
  );
  await write(
    target,
    "tsconfig.json",
    JSON.stringify(
      {
        files: [],
        references: [
          { path: "./tsconfig.app.json" },
          { path: "./tsconfig.node.json" },
        ],
      },
      null,
      2,
    ) + "\n",
  );
  await write(
    target,
    "tsconfig.app.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          allowJs: false,
          skipLibCheck: true,
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          strict: true,
          module: "ESNext",
          moduleResolution: "Bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n",
  );
  await write(
    target,
    "tsconfig.node.json",
    JSON.stringify(
      {
        compilerOptions: {
          composite: true,
          skipLibCheck: true,
          module: "ESNext",
          moduleResolution: "Bundler",
          allowSyntheticDefaultImports: true,
        },
        include: ["vite.config.ts"],
      },
      null,
      2,
    ) + "\n",
  );
  await write(
    target,
    "vite.config.ts",
    `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nimport { VitePWA } from 'vite-plugin-pwa';\nexport default defineConfig({ plugins: [react(), VitePWA({ registerType: 'autoUpdate', includeAssets: ['icons/*.svg'], manifest: { name: '${projectName}', short_name: '${projectName}', display: 'standalone', start_url: '/', theme_color: '#0f172a', background_color: '#f8fafc', icons: [{ src: '/icons/pwa-192.svg', sizes: '192x192', type: 'image/svg+xml' }, { src: '/icons/pwa-512.svg', sizes: '512x512', type: 'image/svg+xml' }, { src: '/icons/pwa-maskable-512.svg', sizes: '512x512', type: 'image/svg+xml', purpose: 'maskable' }] } })] });\n`,
  );
  await write(
    target,
    "src/main.tsx",
    `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport { BrowserRouter } from 'react-router-dom';\nimport App from './App';\nimport './styles.css';\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);\n`,
  );
  await write(target, "src/App.tsx", react(projectName));
  await write(
    target,
    "src/styles.css",
    `:root{font-family:Inter,system-ui,sans-serif;color:#0f172a;background:#f8fafc}body{margin:0}.shell{max-width:720px;margin:18vh auto;padding:2rem}.eyebrow{font-size:.75rem;letter-spacing:.15em;color:#64748b}.actions{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:2rem}button,a{border:0;border-radius:.6rem;padding:.75rem 1rem;background:#0f172a;color:white;text-decoration:none;cursor:pointer}a{background:#e2e8f0;color:#0f172a}`,
  );
  await write(
    target,
    "src/hooks/useInstallPrompt.ts",
    `import { useEffect, useState } from 'react';\nexport function useInstallPrompt(){ const [prompt,setPrompt]=useState<any>(null); useEffect(()=>{ const handler=(event:any)=>{event.preventDefault();setPrompt(event)}; window.addEventListener('beforeinstallprompt',handler); return ()=>window.removeEventListener('beforeinstallprompt',handler)},[]); return {canInstall:!!prompt, install:async()=>{await prompt?.prompt();setPrompt(null)}}; }\n`,
  );
  await write(
    target,
    ".env.example",
    `VITE_FIREBASE_API_KEY=\nVITE_FIREBASE_AUTH_DOMAIN=\nVITE_FIREBASE_PROJECT_ID=\nVITE_FIREBASE_STORAGE_BUCKET=\nVITE_FIREBASE_MESSAGING_SENDER_ID=\nVITE_FIREBASE_APP_ID=\n`,
  );
  if (useFirebase) {
    await write(
      target,
      "src/firebase/firebase.config.ts",
      `import { initializeApp } from 'firebase/app';\n${auth ? "import { getAuth } from 'firebase/auth';\n" : ""}${firestore ? "import { getFirestore } from 'firebase/firestore';\n" : ""}${storage ? "import { getStorage } from 'firebase/storage';\n" : ""}${functions ? "import { getFunctions } from 'firebase/functions';\n" : ""}\nconst config = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET, messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };\nexport const app = initializeApp(config);\n${auth ? "export const auth = getAuth(app);" : ""}\n${firestore ? "export const db = getFirestore(app);" : ""}\n${storage ? "export const storage = getStorage(app);" : ""}\n${functions ? "export const functions = getFunctions(app);" : ""}\n`,
    );
  }
  if (auth) {
    await write(
      target,
      "src/firebase/auth/index.ts",
      `import { GoogleAuthProvider, createUserWithEmailAndPassword, signInAnonymously, signInWithEmailAndPassword, signInWithPopup, signOut } from 'firebase/auth';\nimport { auth } from '../firebase.config';\nexport const loginWithGoogle=()=>signInWithPopup(auth,new GoogleAuthProvider());\nexport const registerWithEmail=(email:string,password:string)=>createUserWithEmailAndPassword(auth,email,password);\nexport const loginWithEmail=(email:string,password:string)=>signInWithEmailAndPassword(auth,email,password);\nexport const loginAnonymously=()=>signInAnonymously(auth);\nexport const logout=()=>signOut(auth);\n`,
    );
    await write(
      target,
      "src/pages/Login.tsx",
      `export default function Login(){return <main className="shell"><h1>Sign in</h1><p>Add your preferred Firebase auth UI here.</p></main>}`,
    );
  }
  if (firestore) {
    await write(
      target,
      "src/firebase/firestore.ts",
      `import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, updateDoc } from 'firebase/firestore';\nimport { db } from './firebase.config';\nexport const getDocument=(name:string,id:string)=>getDoc(doc(db,name,id));\nexport const getDocuments=(name:string)=>getDocs(collection(db,name));\nexport const createDocument=<T>(name:string,data:T)=>addDoc(collection(db,name),data);\nexport const updateDocument=(name:string,id:string,data:Record<string,unknown>)=>updateDoc(doc(db,name,id),data);\nexport const deleteDocument=(name:string,id:string)=>deleteDoc(doc(db,name,id));\n`,
    );
    await write(
      target,
      "firestore.rules",
      `rules_version = '2';\nservice cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read, write: if false; } } }\n`,
    );
    await write(
      target,
      "firestore.indexes.json",
      '{\n  "indexes": [],\n  "fieldOverrides": []\n}\n',
    );
  }
  if (storage) {
    await write(
      target,
      "src/firebase/storage.ts",
      `import { deleteObject, getDownloadURL, ref, uploadBytesResumable } from 'firebase/storage';\nimport { storage } from './firebase.config';\nexport const uploadFileResumable=(path:string,file:File)=>uploadBytesResumable(ref(storage,path),file);\nexport const getFileUrl=(path:string)=>getDownloadURL(ref(storage,path));\nexport const deleteFile=(path:string)=>deleteObject(ref(storage,path));\n`,
    );
    await write(
      target,
      "storage.rules",
      `rules_version = '2';\nservice firebase.storage { match /b/{bucket}/o { match /{allPaths=**} { allow read, write: if false; } } }\n`,
    );
  }
  if (hosting)
    await write(
      target,
      "firebase.json",
      JSON.stringify(
        {
          hosting: {
            public: "dist",
            ignore: ["firebase.json", "**/.*", "**/node_modules/**"],
            rewrites: [{ source: "**", destination: "/index.html" }],
          },
          ...(emulator && {
            emulators: {
              hosting: { port: 5000 },
              firestore: { port: 8080 },
              auth: { port: 9099 },
              storage: { port: 9199 },
            },
          }),
        },
        null,
        2,
      ) + "\n",
    );
  if (functions) {
    await write(
      target,
      "functions/package.json",
      JSON.stringify(
        {
          name: `${projectName}-functions`,
          private: true,
          engines: { node: "20" },
          main: "lib/index.js",
          scripts: {
            build: "tsc",
            serve: "firebase emulators:start --only functions",
            deploy: "firebase deploy --only functions",
          },
          dependencies: {
            "firebase-functions": "^6.0.0",
            "firebase-admin": "^12.0.0",
          },
          devDependencies: { typescript: "^5.6.3" },
        },
        null,
        2,
      ) + "\n",
    );
    await write(
      target,
      "functions/src/index.ts",
      `import { onRequest } from 'firebase-functions/v2/https';\nexport const health = onRequest((_request, response) => response.json({ success: true, message: 'Firebase Functions running' }));\n`,
    );
    await write(
      target,
      "functions/tsconfig.json",
      '{ "compilerOptions": { "module": "NodeNext", "moduleResolution": "NodeNext", "outDir": "lib", "strict": true, "target": "ES2022" }, "include": ["src"] }\n',
    );
  }
  if (android) {
    await write(
      target,
      "android/twa.config.json",
      JSON.stringify(
        {
          packageId: packageName,
          appName: projectName,
          manifestUrl: "https://YOUR_DOMAIN/manifest.webmanifest",
          note: "Run npm run android:init after deploying the PWA.",
        },
        null,
        2,
      ) + "\n",
    );
    await write(
      target,
      "public/.well-known/assetlinks.json",
      '[\n  { "relation": ["delegate_permission/common.handle_all_urls"], "target": { "namespace": "android_app", "package_name": "' +
        packageName +
        '", "sha256_cert_fingerprints": ["REPLACE_WITH_SHA256_FINGERPRINT"] } }\n]\n',
    );
  }
  const icon = (size) =>
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}"><rect width="${size}" height="${size}" rx="${Math.round(size * 0.18)}" fill="#0f172a"/><path d="M${size * 0.24} ${size * 0.5}h${size * 0.52}M${size * 0.5} ${size * 0.24}v${size * 0.52}" stroke="#38bdf8" stroke-width="${Math.round(size * 0.1)}" stroke-linecap="round"/></svg>`;
  await write(target, "public/icons/pwa-192.svg", icon(192));
  await write(target, "public/icons/pwa-512.svg", icon(512));
  await write(target, "public/icons/pwa-maskable-512.svg", icon(512));
  await write(target, "README.md", generatedReadme(projectName, pm));
  if (auth) {
    await write(
      target,
      "src/firebase/auth/phone.ts",
      `import { ConfirmationResult, RecaptchaVerifier, signInWithPhoneNumber } from 'firebase/auth';\nimport { auth } from '../firebase.config';\nexport const createPhoneVerifier=(containerId:string)=>new RecaptchaVerifier(auth,containerId,{size:'invisible'});\nexport const requestPhoneCode=(phone:string,verifier:RecaptchaVerifier):Promise<ConfirmationResult>=>signInWithPhoneNumber(auth,phone,verifier);\n`,
    );
    await write(
      target,
      "src/auth/AuthProvider.tsx",
      `import { onAuthStateChanged, User } from 'firebase/auth';\nimport { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';\nimport { auth } from '../firebase/firebase.config';\nimport * as authApi from '../firebase/auth';\ntype AuthContextValue={user:User|null;loading:boolean}&typeof authApi;\nconst AuthContext=createContext<AuthContextValue|undefined>(undefined);\nexport function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>onAuthStateChanged(auth,(next)=>{setUser(next);setLoading(false)}),[]);const value=useMemo(()=>({user,loading,...authApi}),[user,loading]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}\nexport const useAuth=()=>{const context=useContext(AuthContext);if(!context)throw new Error('useAuth must be used inside AuthProvider');return context};\n`,
    );
    await write(
      target,
      "src/auth/ProtectedRoute.tsx",
      `import { Navigate } from 'react-router-dom';\nimport type { ReactNode } from 'react';\nimport { useAuth } from './AuthProvider';\nexport default function ProtectedRoute({children}:{children:ReactNode}){const {user,loading}=useAuth();if(loading)return <p>Loading...</p>;return user?children:<Navigate to="/login" replace/>}\n`,
    );
    await write(
      target,
      "src/main.tsx",
      `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport { BrowserRouter, Route, Routes } from 'react-router-dom';\nimport App from './App';\nimport Login from './pages/Login';\nimport { AuthProvider } from './auth/AuthProvider';\nimport './styles.css';\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AuthProvider><Routes><Route path="/" element={<App />} /><Route path="/login" element={<Login />} /></Routes></AuthProvider></BrowserRouter></React.StrictMode>);\n`,
    );
  }
  const installCommand = pm === "npm" ? "npm install" : `${pm} install`;
  const runCommand = pm === "npm" ? "npm run dev" : `${pm} dev`;
  if (useFirebase) {
    await write(
      target,
      ".firebaserc",
      JSON.stringify(
        { projects: { default: "YOUR_FIREBASE_PROJECT_ID" } },
        null,
        2,
      ) + "\n",
    );
    await write(
      target,
      "src/firebase/messaging.ts",
      `import { getToken, onMessage } from 'firebase/messaging';\nimport { getMessaging } from 'firebase/messaging';\nimport { app } from './firebase.config';\nexport const messaging = getMessaging(app);\nexport const requestMessagingToken=(vapidKey:string)=>getToken(messaging,{vapidKey});\nexport const listenForMessages=(handler:(payload:unknown)=>void)=>onMessage(messaging,handler);\n`,
    );
  }
  if (auth)
    await write(
      target,
      "src/pages/Login.tsx",
      `import { useState } from 'react';\nimport { loginAnonymously, loginWithEmail, loginWithGoogle, registerWithEmail } from '../firebase/auth';\nexport default function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [register,setRegister]=useState(false);const submit=async()=>{if(register)await registerWithEmail(email,password);else await loginWithEmail(email,password)};return <main className="shell"><h1>Sign in</h1><div className="actions"><button onClick={()=>loginWithGoogle()}>Continue with Google</button><button onClick={()=>loginAnonymously()}>Continue anonymously</button></div><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={submit}>{register?'Create account':'Sign in'}</button><button onClick={()=>setRegister(!register)}>{register?'Use sign in':'Create an account'}</button><p>Phone auth helpers are in src/firebase/auth/phone.ts.</p></main>}\n`,
    );
  await write(
    target,
    "src/components/PwaStatus.tsx",
    `import { useRegisterSW } from 'virtual:pwa-register/react';\nexport default function PwaStatus(){const {needRefresh,updateServiceWorker}=useRegisterSW();if(!needRefresh[0])return null;return <button onClick={()=>updateServiceWorker(true)}>Update available</button>}\n`,
  );
  await write(
    target,
    "src/vite-env.d.ts",
    `/// <reference types="vite/client" />\n/// <reference types="vite-plugin-pwa/react" />\n`,
  );
  if (firestore)
    await write(
      target,
      "src/firebase/firestore-realtime.ts",
      `import { collection, doc, onSnapshot } from 'firebase/firestore';\nimport { db } from './firebase.config';\nexport const subscribeToDocument=(name:string,id:string,onChange:(snapshot:unknown)=>void)=>onSnapshot(doc(db,name,id),onChange);\nexport const subscribeToCollection=(name:string,onChange:(snapshot:unknown)=>void)=>onSnapshot(collection(db,name),onChange);\n`,
    );
  console.log(
    `\n✔ ${projectName} is ready at ${target}\n  cd ${projectName}\n  ${installCommand}\n  ${runCommand}`,
  );
}
main().catch((error) => {
  console.error(`\n✖ ${error.message}`);
  process.exit(1);
});
